stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    outs:
    - CIFAR10
  train:
    cmd: python src/train.py
    deps:
    - CIFAR10
    - src/hparams.py
    - src/train.py
    outs:
    - model.pt
  compute_metrics:
    cmd: python src/compute_metrics.py
    deps:
    - CIFAR10
    - src/compute_metrics.py
    - model.pt
    metrics:
    - final_metrics.json:
        cache: false
